# Generated by Django 5.2.11 on 2026-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture (max 5MB, JPEG/PNG/WebP)', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
