# Generated by Django 5.2.11 on 2026-02-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizens', models.ManyToManyField(blank=True, related_name='grades', to='citizens.citizen')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['name'],
            },
        ),
    ]
